# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6e265ac856dbb375d1cf6334ba1eea62a6da5a2cf25ed6dcd8a21c13dcff2b83a9fb9216e9707f1708844b30edf03a49cc1554dd4dea75ae78d1c7694adc8fc

test:
  secret_key_base: bd752d1201b9d382f9c4bfe4c50b7e845321932f73f7dce5a602c2f60cc0d160da07e6f1badd0707c0fe91ce2a5770fbde2caaea6329224429f70b98009108da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
